(function () {
  const app = window.EscolaZonaSul = window.EscolaZonaSul || {};
  const select = (selector) => document.querySelector(selector);
  const selectAll = (selector) => document.querySelectorAll(selector);

  app.dom = {
    page: document.body.dataset.page || "dashboard",
    schoolGrid: select("#schoolGrid"),
    noticeList: select("#noticeList"),
    eventList: select("#eventList"),
    galleryGrid: select("#galleryGrid"),
    profileList: select("#profileList"),
    registrationsTable: select("#registrationsTable"),
    quickRegisterForm: select("#quickRegisterForm"),
    modalRegisterForm: select("#modalRegisterForm"),
    loginForm: select("#loginForm"),
    forgotPasswordForm: select("#forgotPasswordForm"),
    resetPasswordForm: select("#resetPasswordForm"),
    validationForm: select("#validationForm"),
    noticeForm: select("#noticeForm"),
    eventForm: select("#eventForm"),
    galleryForm: select("#galleryForm"),
    authModal: select("#authModal"),
    authModalTitle: select("#authModalTitle"),
    authModalEyebrow: select("#authModalEyebrow"),
    authTabs: selectAll("[data-auth-tab]"),
    authPanels: selectAll("[data-auth-panel]"),
    closeModalElements: selectAll("[data-close-modal]"),
    navLinks: selectAll("a.nav-link"),
    openAuthModalButton: select("#openAuthModal"),
    openAuthModalSecondaryButton: select("#openAuthModalSecondary"),
    logoutButton: select("#logoutButton"),
    authStatus: select("#authStatus"),
    adminOnlyElements: selectAll("[data-admin-only]"),
    adminContentElements: selectAll("[data-admin-content]"),
    adminAccessMessage: select("#adminAccessMessage"),
    forgotPasswordLink: select("#forgotPasswordLink"),
    backToLoginFromForgotButton: select("#backToLoginFromForgot"),
    requestNewResetCodeButton: select("#requestNewResetCode"),
    resendValidationCodeButton: select("#resendValidationCode"),
    shuffleGalleryButton: select("#shuffleGallery"),
    menuButton: select("#menuButton"),
    toast: select("#toast"),
    sidebar: select("#sidebar"),
    registerSection: select("#cadastros"),
    schoolCount: select("#schoolCount"),
    noticeCount: select("#noticeCount"),
    eventCount: select("#eventCount")
  };
}());
